### ISSUE TITLE
Travis CI builds fail on Consul leader election 

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1077]
[This](https://travis-ci.org/asteris-llc/microservices-infrastructure/jobs/106592772#L2034) happens often:
```
NOTIFIED: [handlers | wait for consul to listen] ****************************** 

failed: [mantl-ci-29-2-worker-002] => {"changed": true, "cmd": ["/usr/local/bin/consul-wait-for-leader.sh"], "delta": "0:00:30.121146", "end": "2016-02-02 22:37:41.006116", "rc": 1, "start": "2016-02-02 22:37:10.884970", "warnings": []}

stdout: No Consul leader elected in 30 seconds

failed: [mantl-ci-29-2-control-02] => {"changed": true, "cmd": ["/usr/local/bin/consul-wait-for-leader.sh"], "delta": "0:00:30.091991", "end": "2016-02-02 22:37:41.078791", "rc": 1, "start": "2016-02-02 22:37:10.986800", "warnings": []}

stdout: No Consul leader elected in 30 seconds

failed: [mantl-ci-29-2-edge-01] => {"changed": true, "cmd": ["/usr/local/bin/consul-wait-for-leader.sh"], "delta": "0:00:30.154212", "end": "2016-02-02 22:37:41.042718", "rc": 1, "start": "2016-02-02 22:37:10.888506", "warnings": []}

...
```

Needs more debugging, but it is clearly a reproducable bug.

**Comment by ohal** [comment]
same here on the openstack http://173.39.245.19/job/PR-to-master-CCS-MI-US-INTERNAL-1-QA-1/
9/10 of builds are failing because of:
```
NOTIFIED: [handlers | wait for consul to listen] ****************************** 
<10.203.53.2> ESTABLISH CONNECTION FOR USER: cloud-user
<10.203.53.2> REMOTE_MODULE command /usr/local/bin/consul-wait-for-leader.sh
<10.203.53.2> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/jenkins/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 10.203.53.2 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1454536065.79-179138234140719 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1454536065.79-179138234140719 && echo $HOME/.ansible/tmp/ansible-tmp-1454536065.79-179138234140719'
<10.203.53.2> PUT /tmp/tmpmMT7nS TO /home/cloud-user/.ansible/tmp/ansible-tmp-1454536065.79-179138234140719/command
<10.203.53.2> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/jenkins/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 10.203.53.2 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/cloud-user/.ansible/tmp/ansible-tmp-1454536065.79-179138234140719/command; rm -rf /home/cloud-user/.ansible/tmp/ansible-tmp-1454536065.79-179138234140719/ >/dev/null 2>&1'
failed: [mi-edge-01] => {"changed": true, "cmd": ["/usr/local/bin/consul-wait-for-leader.sh"], "delta": "0:00:30.115209", "end": "2016-02-03 21:48:16.084994", "rc": 1, "start": "2016-02-03 21:47:45.969785", "warnings": []}
stdout: No Consul leader elected in 30 seconds
```

**Comment by siddharthist** [comment]
It might be because the hosts aren't "big" enough, i.e. don't have enough resources to start electing a leader effectively.

**Comment by ohal** [comment]
currently it's a flavor `CO2-XLarge - 16384gb ram, 50gb disk, 8vcpu` for controls and workers, not sure is it "big" enough ))
which one you suggest to use?

**Comment by ohal** [comment]
let's try to move to `CO2-2XLarge - 32768gb, 50gb, 16vcpu`

**Comment by siddharthist** [comment]
@ohal `CO2-XLarge` actually sounds like plenty, I've deployed sucessfully many times with much smaller hosts. I'm was just speculating wildly ;) I think we'll have to do more digging to find the root cause. Let me know how the `2XL` works for you.

**Comment by ohal** [comment]
does not help, unfortunately
consul still failing [658](http://10.203.54.113/job/PR-to-master-CCS-MI-US-INTERNAL-1-QA-1/658/console)

```
NOTIFIED: [handlers | wait for consul to listen] ****************************** 
<10.203.27.208> ESTABLISH CONNECTION FOR USER: cloud-user
<10.203.27.208> REMOTE_MODULE command /usr/local/bin/consul-wait-for-leader.sh
<10.203.27.208> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/jenkins/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 10.203.27.208 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1454579452.79-68560873372227 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1454579452.79-68560873372227 && echo $HOME/.ansible/tmp/ansible-tmp-1454579452.79-68560873372227'
<10.203.27.208> PUT /tmp/tmpUVa3lZ TO /home/cloud-user/.ansible/tmp/ansible-tmp-1454579452.79-68560873372227/command
<10.203.27.208> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/jenkins/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 10.203.27.208 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/cloud-user/.ansible/tmp/ansible-tmp-1454579452.79-68560873372227/command; rm -rf /home/cloud-user/.ansible/tmp/ansible-tmp-1454579452.79-68560873372227/ >/dev/null 2>&1'
failed: [mi-control-02] => {"changed": true, "cmd": ["/usr/local/bin/consul-wait-for-leader.sh"], "delta": "0:00:30.097562", "end": "2016-02-04 09:51:23.025372", "rc": 1, "start": "2016-02-04 09:50:52.927810", "warnings": []}
stdout: No Consul leader elected in 30 seconds
<10.203.27.206> ESTABLISH CONNECTION FOR USER: cloud-user
<10.203.27.206> REMOTE_MODULE command /usr/local/bin/consul-wait-for-leader.sh
<10.203.27.206> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/jenkins/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 10.203.27.206 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1454579452.77-255974612459761 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1454579452.77-255974612459761 && echo $HOME/.ansible/tmp/ansible-tmp-1454579452.77-255974612459761'
<10.203.27.206> PUT /tmp/tmp8yDbwO TO /home/cloud-user/.ansible/tmp/ansible-tmp-1454579452.77-255974612459761/command
<10.203.27.206> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/jenkins/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 10.203.27.206 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/cloud-user/.ansible/tmp/ansible-tmp-1454579452.77-255974612459761/command; rm -rf /home/cloud-user/.ansible/tmp/ansible-tmp-1454579452.77-255974612459761/ >/dev/null 2>&1'
failed: [mi-worker-002] => {"changed": true, "cmd": ["/usr/local/bin/consul-wait-for-leader.sh"], "delta": "0:00:30.123620", "end": "2016-02-04 09:51:23.023532", "rc": 1, "start": "2016-02-04 09:50:52.899912", "warnings": []}
stdout: No Consul leader elected in 30 seconds
<10.203.27.205> ESTABLISH CONNECTION FOR USER: cloud-user
<10.203.27.205> REMOTE_MODULE command /usr/local/bin/consul-wait-for-leader.sh
<10.203.27.205> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/jenkins/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 10.203.27.205 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1454579452.78-253845231774226 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1454579452.78-253845231774226 && echo $HOME/.ansible/tmp/ansible-tmp-1454579452.78-253845231774226'
<10.203.27.205> PUT /tmp/tmpdVz3jA TO /home/cloud-user/.ansible/tmp/ansible-tmp-1454579452.78-253845231774226/command
<10.203.27.205> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/jenkins/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=cloud-user -o ConnectTimeout=10 10.203.27.205 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/cloud-user/.ansible/tmp/ansible-tmp-1454579452.78-253845231774226/command; rm -rf /home/cloud-user/.ansible/tmp/ansible-tmp-1454579452.78-253845231774226/ >/dev/null 2>&1'
failed: [mi-worker-001] => {"changed": true, "cmd": ["/usr/local/bin/consul-wait-for-leader.sh"], "delta": "0:00:30.140568", "end": "2016-02-04 09:51:23.071727", "rc": 1, "start": "2016-02-04 09:50:52.931159", "warnings": []}
stdout: No Consul leader elected in 30 seconds
```

I'm going to add ansible playbook to gather and show last 500 lines of `/var/log/messages` for further debugging.

**Comment by ohal** [comment]
got some info for debugging:

```
Feb  4 11:17:01 mi-control-03 consul: 2016/02/04 11:17:01 [ERR] dns: error starting tcp server: accept tcp 127.0.0.1:8600: use of closed network connection
Feb  4 11:17:01 mi-control-03 consul: 2016/02/04 11:17:01 [INFO] agent: shutdown complete
Feb  4 11:17:01 mi-control-03 consul: ==> WARNING: LAN keyring exists but -encrypt given, using keyring
Feb  4 11:17:01 mi-control-03 consul: ==> WARNING: WAN keyring exists but -encrypt given, using keyring
Feb  4 11:17:01 mi-control-03 consul: ==> WARNING: Expect Mode enabled, expecting 3 servers
Feb  4 11:17:01 mi-control-03 consul: ==> Starting Consul agent...
Feb  4 11:17:02 mi-control-03 consul: ==> Starting Consul agent RPC...
Feb  4 11:17:02 mi-control-03 consul: ==> Consul agent running!
Feb  4 11:17:02 mi-control-03 consul: Node name: 'mi-control-03'
Feb  4 11:17:02 mi-control-03 consul: Datacenter: 'dc2'
Feb  4 11:17:02 mi-control-03 consul: Server: true (bootstrap: false)
Feb  4 11:17:02 mi-control-03 consul: Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
Feb  4 11:17:02 mi-control-03 consul: Cluster Addr: 192.168.0.10 (LAN: 8301, WAN: 8302)
Feb  4 11:17:02 mi-control-03 consul: Gossip encrypt: true, RPC-TLS: true, TLS-Incoming: true
Feb  4 11:17:02 mi-control-03 consul: Atlas: <disabled>
Feb  4 11:17:02 mi-control-03 consul: ==> Log data will now stream in as it occurs:
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: Ignoring previous leave in snapshot
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: Ignoring previous leave in snapshot
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] raft: Node at 192.168.0.10:8300 [Follower] entering Follower state
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: EventMemberJoin: mi-control-03 192.168.0.10
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: Ignoring previous leave in snapshot
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: Ignoring previous leave in snapshot
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: Attempting re-join to previously known node: mi-worker-002: 192.168.0.7:8301
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: EventMemberJoin: mi-control-03.dc2 192.168.0.10
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] consul: adding LAN server mi-control-03 (Addr: 192.168.0.10:8300) (DC: dc2)
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] consul: adding WAN server mi-control-03.dc2 (Addr: 192.168.0.10:8300) (DC: dc2)
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [WARN] serf: Failed to re-join any previously known node
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [ERR] agent: failed to sync remote state: No cluster leader
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] agent: Joining cluster...
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] agent: (LAN) joining: [192.168.0.10 192.168.0.2 192.168.0.6]
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: EventMemberJoin: mi-control-01 192.168.0.2
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: EventMemberJoin: mi-control-02 192.168.0.6
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [WARN] memberlist: Refuting an alive message
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: EventMemberJoin: mi-worker-002 192.168.0.7
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: EventMemberJoin: mi-worker-001 192.168.0.8
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: EventMemberJoin: mi-worker-003 192.168.0.9
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: EventMemberJoin: mi-edge-01 192.168.0.5
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] serf: Re-joined to previously known node: mi-worker-002: 192.168.0.7:8301
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] consul: adding LAN server mi-control-01 (Addr: 192.168.0.2:8300) (DC: dc2)
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] consul: adding LAN server mi-control-02 (Addr: 192.168.0.6:8300) (DC: dc2)
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] agent: (LAN) joined: 3 Err: <nil>
Feb  4 11:17:02 mi-control-03 consul: 2016/02/04 11:17:02 [INFO] agent: Join completed. Synced with 3 initial agents
Feb  4 11:17:02 mi-control-03 ansible-command: Invoked with creates=None executable=None chdir=None args=/usr/local/bin/consul-wait-for-leader.sh removes=None NO_LOG=None shell=False warn=True
Feb  4 11:17:03 mi-control-03 consul: 2016/02/04 11:17:03 [WARN] raft: EnableSingleNode disabled, and no known peers. Aborting election.
Feb  4 11:17:05 mi-control-03 consul: 2016/02/04 11:17:05 [WARN] raft: Failed to get previous log: 118 log not found (last: 116)
Feb  4 11:17:05 mi-control-03 consul: 2016/02/04 11:17:05 [INFO] raft: Removed ourself, transitioning to follower
Feb  4 11:17:05 mi-control-03 consul: 2016/02/04 11:17:05 [INFO] raft: Removed ourself, transitioning to follower
Feb  4 11:17:05 mi-control-03 consul: 2016/02/04 11:17:05 [INFO] consul: New leader elected: mi-control-01
Feb  4 11:17:05 mi-control-03 consul: 2016/02/04 11:17:05 [INFO] agent: Synced service 'docker'
Feb  4 11:17:05 mi-control-03 consul: 2016/02/04 11:17:05 [INFO] agent: Synced check 'distributive-common-checks'
```

can sent to somebody who is interested in 500 last lines of `/var/log/messages` across the cluster with failing consul

**Comment by ohal** [comment]
here logs from nodes [261](http://173.39.245.19/view/CCS-MI-US-INTERNAL-1-QA-1/job/COMMIT-to-master-CCS-MI-US-INTERNAL-1-QA-1/261/consoleFull)

**Comment by ohal** [comment]
here PR with potential fix https://github.com/CiscoCloud/microservices-infrastructure/pull/1070
it's tested here [663](http://173.39.245.19/view/CCS-MI-US-INTERNAL-1-QA-1/job/PR-to-master-CCS-MI-US-INTERNAL-1-QA-1/663/robot/report/log.html)
here you can see logs gathered from the cluster nodes [663 console](http://173.39.245.19/view/CCS-MI-US-INTERNAL-1-QA-1/job/PR-to-master-CCS-MI-US-INTERNAL-1-QA-1/663/consoleFull)

**Comment by siddharthist** [comment]
Haven't seen this in a bit, is this fixed @sehqlr?

**Comment by sehqlr** [comment]
I never explicitly fixed this, but it has become rare, so I’d be okay with closing the issue, and open a new one if it becomes a problem again.
